### ISSUE TITLE
exception in issue

### ISSUE THREAD

**Issue by poroszd** [poroszd/forum-test#1]
model.indexing.ReindexError: Failed to reindex document at http://stackoverflow.com/questions/24959631
    at model.indexing.ManualIndexService$$anonfun$2$$anonfun$apply$2$$anonfun$apply$1.applyOrElse(ManualIndexService.scala:47) ~[com.samebug.search-1.5.6-SNAPSHOT.jar:1.5.6-SNAPSHOT]
    at model.indexing.ManualIndexService$$anonfun$2$$anonfun$apply$2$$anonfun$apply$1.applyOrElse(ManualIndexService.scala:46) ~[com.samebug.search-1.5.6-SNAPSHOT.jar:1.5.6-SNAPSHOT]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:215) ~[org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.util.Try$.apply(Try.scala:191) ~[org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.util.Failure.recover(Try.scala:215) ~[org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) ~[org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) ~[org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) [org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253) [org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346) [org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.4.jar:na]
Caused by: java.util.NoSuchElementException: None.get
    at scala.None$.get(Option.scala:344) ~[org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.None$.get(Option.scala:342) ~[org.scala-lang.scala-library-2.11.4.jar:na]
    at com.samebug.stackoverflow.StackExchangeClient$$anonfun$1$$anonfun$applyOrElse$1.apply(StackExchangeClient.scala:24) ~[com.samebug.stackoverflow-1.5.6-SNAPSHOT.jar:1.5.6-SNAPSHOT]
    at com.samebug.stackoverflow.StackExchangeClient$$anonfun$1$$anonfun$applyOrElse$1.apply(StackExchangeClient.scala:24) ~[com.samebug.stackoverflow-1.5.6-SNAPSHOT.jar:1.5.6-SNAPSHOT]
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:236) [org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.util.Try$.apply(Try.scala:191) ~[org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.util.Success.map(Try.scala:236) [org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [org.scala-lang.scala-library-2.11.4.jar:na]
    ... 7 common frames omitted

**Comment by poroszd** [comment]
<pre>
model.indexing.ReindexError: Failed to reindex document at http://stackoverflow.com/questions/24959631
    at model.indexing.ManualIndexService$$anonfun$2$$anonfun$apply$2$$anonfun$apply$1.applyOrElse(ManualIndexService.scala:47) ~[com.samebug.search-1.5.6-SNAPSHOT.jar:1.5.6-SNAPSHOT]
    at model.indexing.ManualIndexService$$anonfun$2$$anonfun$apply$2$$anonfun$apply$1.applyOrElse(ManualIndexService.scala:46) ~[com.samebug.search-1.5.6-SNAPSHOT.jar:1.5.6-SNAPSHOT]
    at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:215) ~[org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.util.Try$.apply(Try.scala:191) ~[org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.util.Failure.recover(Try.scala:215) ~[org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) ~[org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.Future$$anonfun$recover$1.apply(Future.scala:324) ~[org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32) [org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121) [org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253) [org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346) [org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [org.scala-lang.scala-library-2.11.4.jar:na]
Caused by: java.util.NoSuchElementException: None.get
    at scala.None$.get(Option.scala:344) ~[org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.None$.get(Option.scala:342) ~[org.scala-lang.scala-library-2.11.4.jar:na]
    at com.samebug.stackoverflow.StackExchangeClient$$anonfun$1$$anonfun$applyOrElse$1.apply(StackExchangeClient.scala:24) ~[com.samebug.stackoverflow-1.5.6-SNAPSHOT.jar:1.5.6-SNAPSHOT]
    at com.samebug.stackoverflow.StackExchangeClient$$anonfun$1$$anonfun$applyOrElse$1.apply(StackExchangeClient.scala:24) ~[com.samebug.stackoverflow-1.5.6-SNAPSHOT.jar:1.5.6-SNAPSHOT]
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:236) [org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.util.Try$.apply(Try.scala:191) ~[org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.util.Success.map(Try.scala:236) [org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [org.scala-lang.scala-library-2.11.4.jar:na]
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235) [org.scala-lang.scala-library-2.11.4.jar:na]
    ... 7 common frames omitted
</pre>

**Comment by poroszd** [comment]
java.io.FileNotFoundException: /opt/dev/projects/github/liferay-portal/modules/apps/translator/build.xml (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:249)

**Comment by poroszd** [comment]
<pre>
java.io.FileNotFoundException: /opt/dev/projects/github/liferay-portal/modules/apps/translator/build.xml (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:249)
</pre>

**Comment by poroszd** [comment]
```
java.io.FileNotFoundException: /opt/dev/projects/github/liferay-portal/modules/apps/translator/build.xml (No such file or directory)
    at java.io.FileInputStream.open(Native Method)
    at java.io.FileInputStream.<init>(FileInputStream.java:146)
    at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:249)
```
